### ISSUE TITLE
/speedtest

### ISSUE THREAD

**Issue by Mcrich23** [CMarcoo/SystemInfo#14]
How do I configure speed test? I keep getting the error that it is not configured correctly. Thanks!

**Comment by CMarcoo** [comment]
Hello, I will look into this issue.
I am currently aware of issues with the external library imported for speedtests.

**Comment by CMarcoo** [comment]
Issue has been fixed into the latest version.
Speedtest seems to work.

![image](https://github.com/CMarcoo/SystemInfo/assets/29604693/ff623702-1426-45db-b179-2ea8341168c7)
