### ISSUE TITLE
Reducing Speed Test Spam

### ISSUE THREAD

**Issue by ColemanMaximus** [CMarcoo/SystemInfo#16]
The speedtest command is quite useful, but I feel it sends more than enough messages for progress. Maybe reduce it to sending one progress message every couple of seconds instead of flooding the chat too much. It's mostly duplicates for me.

**Comment by CMarcoo** [comment]
Yes. Next update will fix this.

**Comment by CMarcoo** [comment]
Fixed. 1.8.7-SNAPSHOT
